const router = require("express").Router();
const User = require("../model/User");
const bcrypt = require("bcryptjs");
const { loginValidation, registerValidation } = require("../validation");
const jwt = require('jsonwebtoken');
const path = require('path');

router.post("/register", async (req, res) => {
  // validate before we submit data
  const validation = registerValidation(req.body);

  if (validation.error) return res.status(400).send(validation);

  const emailExist = await User.findOne({
    email: req.body.email
  });

  if (emailExist) return res.status(400).send("Email already exists");

  // hash password
  const salt = await bcrypt.genSalt(10);
  const hashPassword = await bcrypt.hash(req.body.password, salt);

  const user = new User({
    name: req.body.name,
    email: req.body.email,
    password: hashPassword
  });
  try {
    const saveUser = await user.save();
    res.send({ userId: saveUser._id });
  } catch (error) {
    res.status(400).send(error);
  }
});

router.post("/login", async (req, res) => {
  // validate before we submit data
  const validation = loginValidation(req.body);

  if (validation.error) return res.status(400).send(validation);

  const user = await User.findOne({
    email: req.body.email
  });

  if (!user) return res.status(400).send("Email is not found");

  // password is correct
  const validPass = await bcrypt.compare(req.body.password, user.password);

  if (!validPass) return res.status(400).send("Invalid password");

  // create and assign a token
  const token = jwt.sign({
    sub: "5JLbsvc1FzZy9qRT8Y8tkk", //keyId generated by eg create
    name: "tuanvinhtl",
    iat: Math.floor(Date.now() / 1000) - 30,
    // _id: user._id
  }, process.env.TOKEN_SECRET,{ expiresIn: 900});
  res.header('Authorization', 'bearer ' + token).send('bearer ' + token)
});

router.get("/login-page",(req, res) => {
  return res.sendFile(path.join(__dirname + '/render-page/login.html'));;
});

module.exports = router
